seed_everything: 2022
trainer:
  logger: true
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
    init_args:
      patience: 5
      min_delta: 0.001
      verbose: true
      monitor: val_loss
      mode: min
  logger:
      - class_path: pytorch_lightning.loggers.NeptuneLogger
      init_args:
          
  default_root_dir: /home/yananlong/DDI/
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: null
  gpus: 1
  auto_select_gpus: true
  tpu_cores: null
  ipus: null
  log_gpu_memory: true
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 2
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 0.1
  limit_val_batches: 0.1
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: null
  log_every_n_steps: 50
  accelerator: null
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: true
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: true
  terminate_on_nan: null
model:
  batch_size: 256
  act: leakyrelu
  fp_nlayers: 4
  fp_in: null
  fp_hid: 256
  gnn_name: pyg_nn.GINEConv
  gnn_nlayers: 4
  gnn_in: 9
  gnn_hid: 256
  dec_nlayers: 4
  dec_hid: 256
  out_dim: null
  use_custom_MLP: false
  final_concat: true
  dropout: 0
  top_k: 5
data:
  root: /home/yananlong/DDI/Data
  kind: morgan
  data_dir: /home/yananlong/DDI/Data
  include_neg: true
  train_prop: 0.8
  val_prop: 0.5
  batch_size: 256
ckpt_path: null
